// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA5gQWrD6M_yYGQpFcJYEkfQ6v8NNcTE0',
    appId: '1:604247727598:web:38f0c1c1ccdd8479ea42ff',
    messagingSenderId: '604247727598',
    projectId: 'gen-lang-client-0377094028',
    authDomain: 'gen-lang-client-0377094028.firebaseapp.com',
    storageBucket: 'gen-lang-client-0377094028.firebasestorage.app',
    measurementId: 'G-3GHCH97XM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxgWC3vq7N5P61zhQkPnzi5VEi8ZWJ9g',
    appId: '1:604247727598:android:e6a278e24c72f4baea42ff',
    messagingSenderId: '604247727598',
    projectId: 'gen-lang-client-0377094028',
    storageBucket: 'gen-lang-client-0377094028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFa2gZASzLA3gTakROqrvEBWIQ3Yz3mZ4',
    appId: '1:604247727598:ios:7cc3d6e22ab506c0ea42ff',
    messagingSenderId: '604247727598',
    projectId: 'gen-lang-client-0377094028',
    storageBucket: 'gen-lang-client-0377094028.firebasestorage.app',
    iosBundleId: 'com.example.aiper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFa2gZASzLA3gTakROqrvEBWIQ3Yz3mZ4',
    appId: '1:604247727598:ios:7cc3d6e22ab506c0ea42ff',
    messagingSenderId: '604247727598',
    projectId: 'gen-lang-client-0377094028',
    storageBucket: 'gen-lang-client-0377094028.firebasestorage.app',
    iosBundleId: 'com.example.aiper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA5gQWrD6M_yYGQpFcJYEkfQ6v8NNcTE0',
    appId: '1:604247727598:web:b9700d5ff20f042cea42ff',
    messagingSenderId: '604247727598',
    projectId: 'gen-lang-client-0377094028',
    authDomain: 'gen-lang-client-0377094028.firebaseapp.com',
    storageBucket: 'gen-lang-client-0377094028.firebasestorage.app',
    measurementId: 'G-7HKPDQTV77',
  );
}
